### ISSUE TITLE
calendar days to local cache

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#118]
Aktuálně lze pro daný rozsah dní dotáhnout, které z nich jsou market days. Toto je poplatné zatím pouze pro US Market  a Alpacu. 

```python
market_open_days = fetch_calendar_data(start_date, end_date)

vráceno:
[{   'close': datetime.datetime(2024, 3, 1, 16, 0),
    'date': datetime.date(2024, 3, 1),
    'open': datetime.datetime(2024, 3, 1, 9, 30)}, {   'close': datetime.datetime(2024, 3, 4, 16, 0),
    'date': datetime.date(2024, 3, 4),
    'open': datetime.datetime(2024, 3, 4, 9, 30)}]
``` 

Nyní se pro každé zavolání fetch_calendar_data volá Alpaca a toto není výhodné pro backtesty a performance. Vzhledem k tomu, že tyto data se často neměnní (spíše přibývají) je třeba implementovat cache mechanismus, který uloží data do lokální cache a s každým voláním pak přistupuje do cache.

Pokud v cache data nejsou pro toto období, dotáhne data např. 100dní dopředu. Pokud data existujíc dotáhnout z cache, případně pokud bude zbývat např. už jen 50 tak se dotáhnne dalších 200. Triggerována requestem.

Služba také umožní atribut 'dont_use_cache (def. False)', který data dotáhne z Alpaca a uloží je.

Rozhranní a vracený formát se jinak neměnní (služba je hodně využitá ve stávajícím kódu).

**Comment by drew2323** [comment]
@pvlasak tohle bude ideální další issue

**Comment by drew2323** [comment]
zvážit implementace:

- https://github.com/rsheftel/pandas_market_calendars
-

**Comment by pvlasak** [comment]
Solved in #213
