### ISSUE TITLE
Runmanager - support of market attribute

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#145]
Curenntly only us market is supported, that means that when scheduler engine processes scheduled records, it first checks whether the market is open at current time. This is hardcoded. However this check should be done based on the "market" column which defines type of market (currently just US or none=24hrs open)  

Will be realized as new "market" column in runmanager table and also enum in runmanagerrecord class.

This would also allow better testing of strategies and schedulers, as currently it is not possible to test scheduled jobs outside of market days. That would be possible just by temporarily changing market attribute on frontend.

values and behaviour
- 24hrs - no check is done
- US  - checks if us market is open this day.  Days are fetched from calendar api

Note. 24hrs value might be realized as Null in market_column.

When scheduled record is processed it does the "is market day" check based on value of "market" attributte.

Also the attribute should be visible on frontend, in scheduled records list and addedit modal

**Responsibility split:**

backend
- db column
- model class
- backend functions/apis
- functions called by apsscheduler jobs

frontend
- new column in datatables, modals and its handling

**Comment by pvlasak** [comment]
Pull request #185
