### ISSUE TITLE
use load_dotenv() function to access env variable

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#157]
For better control over environment variables over different dev/prod/test environments.

All environment variables that app uses, will be in separate file in app root dir (.gitignored)

More details in [gemini conversation](https://g.co/gemini/share/14bb98966b76).

Responsibility split:
- python code change
- migration script
- cookbook/update of installation

**Comment by pvlasak** [comment]
Pull request #195

**Comment by pvlasak** [comment]
Pull request #195
