### ISSUE TITLE
náhrada getCalendar API - create your own

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#42]
Alpaca get Calendar is very often unavailable, the backtests depends on it heavily, make your own.

Vytvořit vlastní cachovací komponentu, aby se nemuselo pro každý request dotahovat z Alpaca serveru.
Cache bude obsahovat např. sysdate + 200 dní záznamů a pokud bude zbývat např. už jen 50 tak se dotáhnne dalších 200. Triggerována requestem.

**Comment by drew2323** [comment]
duplicate to #118

**Comment by pvlasak** [comment]
Solved in #213
